/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tl.osv.kernel.data.params;

import com.tl.osv.Log;
import com.tl.osv.Mls;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author root
 */
public class SelectParameterGUI extends javax.swing.JPanel {
    SelectParameter param;
    /**
     * Creates new form SelectParameterGUI
     */
    public SelectParameterGUI(SelectParameter param) {
        initComponents();
        this.param = param;

        DefaultComboBoxModel model = new DefaultComboBoxModel( param.getSelectionList() );
        comboBoxSelector.setModel(model);
        
        comboBoxSelector.setSelectedIndex(param.getAsInteger());
        
        comboBoxSelector.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try{
                    param.setAsInteger(comboBoxSelector.getSelectedIndex());
                    param.getParent().commit();
                }catch(Exception ex){
                    Log.exception(ex);
                }
            }
        });
        
        labelName.setText(Mls.translate(param.getName()));
        comboBoxSelector.setToolTipText(Mls.translate(param.getDescription()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelName = new javax.swing.JLabel();
        comboBoxSelector = new javax.swing.JComboBox();

        labelName.setText("jLabel1");

        comboBoxSelector.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboBoxSelector, 0, 356, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(comboBoxSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(labelName))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboBoxSelector;
    private javax.swing.JLabel labelName;
    // End of variables declaration//GEN-END:variables
}
